### ISSUE TITLE
Documentation change

### ISSUE THREAD

**Issue by cgriffith99** [stokito/grails-cookie#35]
It appears that the documentation is a little off if you want to change defaultStrategy for the plugin:

Instead of:

grails.plugins.cookie.path.defaultStrategy = 'context'

This works for me:

grails.plugins.cookie.defaultStrategy = 'context'

**Comment by stokito** [comment]
Yes, thanks for your report.
It's a bug, and I will fix it right now.

**Comment by stokito** [comment]
Sorry, I'll fix it latter, tomorrow.

**Comment by cgriffith99** [comment]
Thanks for the quick response to this!

**Comment by stokito** [comment]
I fixed this issue in plugin versions 1.2 (for grails 2.2) and 1.4 (for Grails 2.4+).
Thanks for your report, and could you check that all works as expected?

**Comment by stokito** [comment]
Seems like it was fixed
