### ISSUE TITLE
Publish to bintray and add to Grails Plugin Repo

### ISSUE THREAD

**Issue by ctoestreich** [stokito/grails-cookie#45]
This needs to be pushed to bintray as an artifact.

I have pushed to my local bintray to use this in grails 3.  You can checkout my build.gradle here or if you want me to publish we can move the plugin to the grails-plugin-consortium group and I can give you access to this plugin again

https://github.com/ctoestreich/grails-cookie

https://github.com/Grails-Plugin-Consortium/

Let me know.  I would like to use the grails version not my custom published one.

**Comment by ctoestreich** [comment]
Any Word?

**Comment by stokito** [comment]
Hi @ctoestreich 

Unfortunately last few mounthes I hadn't enough time to maintain this plugin. I changed my work and now I don't work with Grails and I haven't any expirience with last version Grails 3 and Gradle.
There was some pull requests to this plugin to make it comatible with Grails 3 but I don't check them. For example this https://github.com/stokito/grails-cookie/pull/44
If you can maintain it now - I would be very thankful to you.
We can transfer this plugin to Grails-Plugin-Consortium and release a new version on plugins.grails.org. 

So, should I transfer the plugin to you? :-)

**Comment by ctoestreich** [comment]
Go ahead and transfer.  I will make you a maintainer of the plugin if you ever want to work on it again.
Christian 


    On Monday, December 7, 2015 9:47 AM, Sergey Ponomarev <notifications@github.com> wrote:
 

 Hi @ctoestreich Unfortunately last few mounthes I hadn't enough time to maintain this plugin. I changed my work and now I don't work with Grails and I haven't any expirience with last version Grails 3 and Gradle.
There was some pull requests to this plugin to make it comatible with Grails 3 but I don't check them. For example this #44
If you can maintain it now - I would be very thankful to you.
We can transfer this plugin to Grails-Plugin-Consortium and release a new version on plugins.grails.org. So, should I transfer the plugin to you? :-)—

**Comment by stokito** [comment]
Hi @ctoestreich 
I need an adming right in Grails-Plugin-Consortium to make a transfer: "You don’t have admin rights to Grails-Plugin-Consortium"

    Transfer ownership
    Transfer this repository to another user or to an organization where you have admin rights.


Could you add me a rights and after transfer revert them?

**Comment by ctoestreich** [comment]
You can simply put a deprecated note in your read me and link to the new repo.  I have cloned and pushed.  Will get out on grails 3 plugin bintray
